<a href="https://colab.research.google.com/github/wodzmistrz/iwgia_zaoczni/blob/master/Tensors_Crash_Course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip3 install torch

In [0]:
import torch
import numpy as np

In [0]:
v = torch.tensor([1,2,3,4,5,6])
print(v[1:])

tensor([2, 3, 4, 5, 6])


In [0]:
f = torch.FloatTensor([1,2,3,4,5,6])
print(f.size())

torch.Size([6])


In [0]:
v.view(3,-1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [0]:
a = np.array([1,2,3,4,5])
tensor_cnv = torch.from_numpy(a)
print(tensor_cnv)
print(tensor_cnv.type())

tensor([1, 2, 3, 4, 5])
torch.LongTensor


In [0]:
numpy_cnv = tensor_cnv.numpy()
print(numpy_cnv)

[1 2 3 4 5]
